import {
  CreateHotelRoomInput,
  CreateHotelRoomOutput,
  DeleteHotelRoomInput,
  DeleteHotelRoomOutput,
  FetchAllHotelRoomInput,
  FetchAllHotelRoomOutput,
  FetchOneHotelRoomInput,
  FetchOneHotelRoomOutput,
  UpdateHotelRoomInput,
  UpdateHotelRoomOutput,
} from "./room.dto";
import {
  CreateTypeInput,
  CreateTypeOutput,
  DeleteHotelRoomTypeInput,
  DeleteHotelRoomTypeOutput,
  FetchAllHotelRoomTypeInput,
  FetchAllHotelRoomTypeOutput,
  FetchOneHotelRoomTypeInput,
  FetchOneHotelRoomTypeOutput,
  UpdateHotelRoomTypeInput,
  UpdateHotelRoomTypeOutput,
} from "./room_type.dto";

export {
  CreateTypeInput,
  CreateTypeOutput,
  FetchAllHotelRoomTypeInput,
  FetchAllHotelRoomTypeOutput,
  FetchOneHotelRoomTypeInput,
  FetchOneHotelRoomTypeOutput,
  UpdateHotelRoomTypeInput,
  UpdateHotelRoomTypeOutput,
  DeleteHotelRoomTypeInput,
  DeleteHotelRoomTypeOutput,
  CreateHotelRoomInput,
  CreateHotelRoomOutput,
  FetchAllHotelRoomInput,
  FetchAllHotelRoomOutput,
  FetchOneHotelRoomInput,
  FetchOneHotelRoomOutput,
  UpdateHotelRoomInput,
  UpdateHotelRoomOutput,
  DeleteHotelRoomInput,
  DeleteHotelRoomOutput,
};
