import { CreateHotelAmenityInput, CreateHotelAmenityOutput, FetchAllHotelAmenityOutput, FetchOneHotelAmenityInput, FetchOneHotelAmenityOutput, UpdateHotelAmenityInput, UpdateHotelAmenityOutput, DeleteHotelAmenityInput, DeleteHotelAmenityOutput } from "./amenity.dto";
import { CreateHotelAmenityMenuInput, CreateHotelAmenityMenuOutput, DeleteHotelAmenityMenuInput, DeleteHotelAmenityMenuOutput, FetchAllHotelAmenityMenuInput, FetchAllHotelAmenityMenuOutput, FetchOneHotelAmenityMenuInput, FetchOneHotelAmenityMenuOutput, UpdateHotelAmenityMenuInput, UpdateHotelAmenityMenuOutput } from "./amenity_menu.dto";
import { CreateHotelBookingInput, CreateHotelBookingOutput, FetchAllHotelBookingOutput, FetchOneHotelBookingInput, FetchOneHotelBookingOutput, UpdateHotelBookingInput, UpdateHotelBookingOutput, DeleteHotelBookingInput, DeleteHotelBookingOutput, CancelHotelBookingInput, CancelHotelBookingOutput } from "./booking.dto";
import { CreateHotelOrderInput, CreateHotelOrderOutput, FetchAllHotelOrderOutput, FetchOneHotelOrderInput, FetchOneHotelOrderOutput, UpdateHotelOrderInput, UpdateHotelOrderOutput, DeleteHotelOrderInput, DeleteHotelOrderOutput } from "./order.dto";
import {
  CreateHotelRoomInput,
  CreateHotelRoomOutput,
  DeleteHotelRoomInput,
  DeleteHotelRoomOutput,
  FetchAllHotelRoomInput,
  FetchAllHotelRoomOutput,
  FetchOneHotelRoomInput,
  FetchOneHotelRoomOutput,
  UpdateHotelRoomInput,
  UpdateHotelRoomOutput,
} from "./room.dto";
import {
  CreateTypeInput,
  CreateTypeOutput,
  DeleteHotelRoomTypeInput,
  DeleteHotelRoomTypeOutput,
  FetchAllHotelRoomTypeInput,
  FetchAllHotelRoomTypeOutput,
  FetchOneHotelRoomTypeInput,
  FetchOneHotelRoomTypeOutput,
  UpdateHotelRoomTypeInput,
  UpdateHotelRoomTypeOutput,
} from "./room_type.dto";

export {
  CreateTypeInput,
  CreateTypeOutput,
  FetchAllHotelRoomTypeInput,
  FetchAllHotelRoomTypeOutput,
  FetchOneHotelRoomTypeInput,
  FetchOneHotelRoomTypeOutput,
  UpdateHotelRoomTypeInput,
  UpdateHotelRoomTypeOutput,
  DeleteHotelRoomTypeInput,
  DeleteHotelRoomTypeOutput,
  CreateHotelRoomInput,
  CreateHotelRoomOutput,
  FetchAllHotelRoomInput,
  FetchAllHotelRoomOutput,
  FetchOneHotelRoomInput,
  FetchOneHotelRoomOutput,
  UpdateHotelRoomInput,
  UpdateHotelRoomOutput,
  DeleteHotelRoomInput,
  DeleteHotelRoomOutput,
  CreateHotelAmenityInput,
  CreateHotelAmenityOutput,
  FetchAllHotelAmenityOutput,
  FetchOneHotelAmenityInput,
  FetchOneHotelAmenityOutput,
  UpdateHotelAmenityInput,
  UpdateHotelAmenityOutput,
  DeleteHotelAmenityInput,
  DeleteHotelAmenityOutput,
  CreateHotelAmenityMenuInput,
  CreateHotelAmenityMenuOutput,
  FetchAllHotelAmenityMenuInput,
  FetchAllHotelAmenityMenuOutput,
  FetchOneHotelAmenityMenuInput,
  FetchOneHotelAmenityMenuOutput,
  UpdateHotelAmenityMenuInput,
  UpdateHotelAmenityMenuOutput,
  DeleteHotelAmenityMenuInput,
  DeleteHotelAmenityMenuOutput,
  CreateHotelOrderInput,
  CreateHotelOrderOutput,
  FetchAllHotelOrderOutput,
  FetchOneHotelOrderInput,
  FetchOneHotelOrderOutput,
  UpdateHotelOrderInput,
  UpdateHotelOrderOutput,
  DeleteHotelOrderInput,
  DeleteHotelOrderOutput,
  CreateHotelBookingInput,
  CreateHotelBookingOutput,
  FetchAllHotelBookingOutput,
  FetchOneHotelBookingInput,
  FetchOneHotelBookingOutput,
  UpdateHotelBookingInput,
  UpdateHotelBookingOutput,
  DeleteHotelBookingInput,
  DeleteHotelBookingOutput,
  CancelHotelBookingInput,
  CancelHotelBookingOutput
};
